AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Lambda Instagram Followers Chart"

Resources:
  ScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin
      Handler: scraper
      Runtime: go1.x
      Timeout: 300

      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - 
              Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt LogsTable.Arn

      Environment:
        Variables:
          IG_USERNAME: ""
          LOGS_TABLE: !Ref LogsTable

  ScheduledScraper:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "cron(0 0 ? * * *)"
      State: ENABLED
      Targets:
        -
          Arn:
            Fn::GetAtt:
              - ScraperFunction
              - Arn
          Id: TargetFunctionV1
    
  LogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - 
          AttributeName: "time"
          AttributeType: "S"
        - 
          AttributeName: "username"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "username"
          KeyType: "HASH"
        - 
          AttributeName: "time"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"

Outputs:
  LogsTable:
    Description: "Logs Dynamo DB table"
    Value:
      Fn::GetAtt:
      - LogsTable
      - Arn